version: '3.8'

services:
  rushdeal_postgres:
    image: postgres:16-alpine
    container_name: rushdeal_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rushdeal_db
      POSTGRES_USER: rushdeal
      POSTGRES_PASSWORD: rushdeal
    ports:
      - "15432:5432"
    volumes:
      - rushdeal_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rushdeal -d rushdeal_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  rushdeal_queue_redis: # 서비스 이름은 rushdeal_redis로 설정합니다.
    image: redis:7-alpine
    container_name: rushdeal_queue_redis
    restart: unless-stopped
    ports:
      - "6380:6379" # 6379가 Redis 기본 포트이나, 호스트 포트를 6380으로 설정하여 기존 충돌을 피합니다.
    volumes:
      - rushdeal_queue_redis_data:/data # 데이터 영속성을 위한 볼륨
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  rushdeal_order_redis:
    image: redis:7-alpine
    container_name: rushdeal_order_redis
    restart: unless-stopped
    ports:
      - "6381:6379"
    volumes:
      - rushdeal_order_redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  # Zookeeper
  rushdeal_zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: rushdeal_zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "12181:2181"

  # Kafka
  rushdeal_kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: rushdeal_kafka
    restart: unless-stopped
    depends_on:
      - rushdeal_zookeeper
    ports:
      - "19092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: rushdeal_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://rushdeal_kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  rushdeal_pg_data:
  rushdeal_queue_redis_data:
  rushdeal_order_redis_data:
