spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/rushdeal_db
    username: rushdeal
    password: rushdeal
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8010

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}