spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
      -
  application:
    name: order-service

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never       # 스키마는 schema.sql로 생성
    properties:
      org:
        quartz:
          scheduler:
            instanceName: OrderScheduler
            instanceId: AUTO

          dataSource:
            main:                          # ★ Quartz가 인식하는 이름
              driver: org.postgresql.Driver
              URL: ${DB_URL}
              user: ${DB_USERNAME}
              password: ${DB_PASSWORD}

          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            dataSource: main               # ★ Quartz가 main datasource 사용
            tablePrefix: quartz_schema.QRTZ_
            isClustered: true

          threadPool:
            threadCount: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: order_schema     # ★ JPA는 order_schema 사용

  sql:
    init:
      mode: always                       # schema.sql 실행

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8050

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: localhost
    prefer-ip-address: true
