spring:
  application:
    name: order-service

  batch:
    jdbc:
      initialize-schema: always # 배치 메타 테이블 자동 생성
    job:
      enabled: false  # 애플리케이션 시작 시 자동 실행 방지 (Quartz가 관리)

  quartz:
    job-store-type: jdbc  # DB에 스케줄 정보 저장
    jdbc:
      initialize-schema: always # Quartz 테이블 자동 생성
    properties:
      org:
        quartz:
          scheduler:
            instanceName: OrderScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            dataSource: quartzDataSource
            tablePrefix: QRTZ_
            isClustered: true  # 클러스터 모드 (다중 인스턴스 환경)
          threadPool:
            threadCount: 10

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: order_schema

  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8050

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: localhost
    prefer-ip-address: true
